# Generated by Django 4.2.6 on 2023-10-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('titulo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nota', models.TextField()),
            ],
        ),
    ]
